### PR TITLE
fix(plugins/plugin-logui): improve log rendering

### LINKED ISSUE #291: Usability issues with logging feature
The logging feature in KUI has some usability issues; here are a few problems I've noticed:

1.  [ ] Logs seem to be capped at 20 or less lines.
2.  [ ] Logs are presented in a table format, as opposed to a more conventional logging format.
3.  [x] If `-f` is used, the browser will freeze up because an extraordinary amount of HTML is being generated (a `span` for each letter).
4.  [ ] Long log lines will get truncated at the table border, user cannot scroll to see the rest; nor should they have to? 
5.  [ ] No search feature in logs.

It would be great to get a UX designer's input to improve this feature.

### LINKED ISSUE #322: tekton plugin does not load in production client builds
in dev mode, it seems fine, but in production mode (i.e. webpack production mode) builds:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number

coming from plugin-tekton/src/preload:

```typescript
  const specialPath = join(dirname(require.resolve('@kui-shell/plugin-tekton/package.json')), 'samples/@demos')
  augmentModuleLoadPath(specialPath, { prefix: '@demos/tekton', command: 'tekton flow' })
```

### PR DESCRIPTION
**Pull request by starpit**
stop using tables to present logs, and instead present mostly raw logs, filtered only through regexp for formatting

Fixes #291

### CODE REVIEW

File: plugins/plugin-logui/src/controller/kubectl/logs.ts [hunk 1]
```diff
@@ -72,44 +43,118 @@ async function getLogsAsTable(args: Arguments<LogOptions>) {
...
+    const since = '10s'
+    args.parsedOptions.since = since
+    args.argv.push('--since=since')
+    args.command = args.command + ' --since=10s'
+  }
+
+  // if we are not streaming, and the user has not specified a
+  // "--tail", then add one, for the same reason
+  if (!streamed && !args.parsedOptions.tail) {
+    const tail = 30
```
Comment (hanqiuzh) [inline plugins/plugin-logui/src/controller/kubectl/logs.ts]: so it's hard coded to 30 lines if user didn't add a `--tail`?

File: plugins/plugin-logui/src/controller/kubectl/logs.ts [hunk 2]
```diff
@@ -72,44 +43,118 @@ async function getLogsAsTable(args: Arguments<LogOptions>) {
...
+      // _ is one chunk of streaming output
+      return async (_: Streamable) => {
+        if (args.block['isCancelled']) {
+          ptyJob.abort()
+        } else if (typeof _ === 'string') {
+          // we only know how to handle strings
+          if (/\n$/.test(_)) {
+            const joined = curLine ? curLine + _ : _
+            // eslint-disable-next-line no-control-regex
+            const fullLine = /\x1b/.test(joined)
```
Comment (hanqiuzh) [inline plugins/plugin-logui/src/controller/kubectl/logs.ts]: why it's checking `\x1b` here? 
so if there is `\x1b`, don't do any color replace, but use ansi directly?

File: plugins/plugin-logui/src/controller/kubectl/logs.ts [hunk 3]
```diff
@@ -14,56 +14,27 @@
...
-async function getLogsAsTable(args: Arguments<LogOptions>) {
-  const raw = await doExecWithStdout(args, prepareCommand)
+const debug = Debug('plugin-logui/controller/kubectl/logs')
 
-  return formatAsTable(raw, {
-    name: args.argvNoOptions[args.argvNoOptions.indexOf('logs') + 1],
-    namespace: (args && getNamespace(args)) || 'default'
-  })
-}
+const literal = (match, p1, p2) => `${p1}${colors.blue(p2)}`
```
Comment (hanqiuzh) [inline plugins/plugin-logui/src/controller/kubectl/logs.ts]: all these color are hard coded? will it be affected by themes

Comment (starpit) [reply plugins/plugin-logui/src/controller/kubectl/logs.ts]: these are using ansi control codes. the theme alignment comes from plugin-kubeui-client/web/css/colors.css

File: plugins/plugin-logui/src/controller/kubectl/logs.ts (hunk 2 above)
Comment (starpit) [reply plugins/plugin-logui/src/controller/kubectl/logs.ts]: i meant to add a comment, thanks for the poke. the check here is: if the output from the PTY already contains ANSI control characters, then we won't add any of our own. \x1b is ESCAPE

File: plugins/plugin-logui/src/controller/kubectl/logs.ts [hunk 4]
```diff
@@ -14,102 +14,160 @@
...
+            const joined = curLine ? curLine + _ : _
+            // if the output from the PTY already contains ANSI
+            // control characters, then we won't add any of our
+            // own. \x1b is ESCAPE
+            // eslint-disable-next-line no-control-regex
+            const fullLine = /\x1b/.test(joined)
+              ? joined
+              : joined
+                  // informational extras
+                  .replace(/(\[.*?\])/g, (match, p1) => colors.gray(p1))
```
Comment (hanqiuzh) [inline plugins/plugin-logui/src/controller/kubectl/logs.ts]: These rules looks good, but have some concerns:
1.  Will it be better to wrap all these rules into a function
2. All rules seems targeting to one format. Will it be nice if add some comments with examples of the format?
3. Looks like a lot of replace (11+ global matches without ^&), not sure whether it will slow the system down. 
    Is these code run on the webpack side or host(server/proxy) side? 
    If on webpack side, I think we don't need to worry about it.

Comment (starpit) [reply plugins/plugin-logui/src/controller/kubectl/logs.ts]: this code is run on the client, no the proxy server

Comment (starpit) [reply plugins/plugin-logui/src/controller/kubectl/logs.ts]: pushed a cleanup: separated out decorateLogLines and added comments and examples!
